package br.com.solutis.jogo.de.adivinhacao;

import java.util.Random;



public class ViewJogoDeAdivinhacao extends javax.swing.JFrame {
    
    int tentativas = 5;
    Random random = new Random();
    int numeroSorteado = random.nextInt(100)+1;
    boolean respostaCerta = false;
    
    public ViewJogoDeAdivinhacao() {
        initComponents();
        
        Random random = new Random();
        numeroSorteado = random.nextInt(100) + 1;
        txtStatusTentativas.setText("Tentativas restantes: " + tentativas);
        txtFeedBack.setText("Por favor, digite um número entre 1 e 100.");
        botaoJogarNovamente.setVisible(false);
        botaoFecharJogo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloMaior = new javax.swing.JLabel();
        tituloMenor = new javax.swing.JLabel();
        txtInputTentativa = new javax.swing.JLabel();
        inputTentativa = new javax.swing.JTextField();
        botaoEnviarTentativa = new javax.swing.JButton();
        txtFeedBack = new javax.swing.JLabel();
        txtStatusTentativas = new javax.swing.JLabel();
        botaoJogarNovamente = new javax.swing.JButton();
        botaoFecharJogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo de Advinhação");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        tituloMaior.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        tituloMaior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloMaior.setText("JOGO DE ADIVINHAÇÃO");
        tituloMaior.setName("tituloMaior"); // NOI18N

        tituloMenor.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        tituloMenor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloMenor.setText("TENTE ADIVINHAR QUAL NÚMERO DE 1 ATÉ 100 FOI SORTEADO!");

        txtInputTentativa.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        txtInputTentativa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInputTentativa.setText("DIGITE UM NUMERO:");

        inputTentativa.setBackground(new java.awt.Color(153, 204, 255));
        inputTentativa.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        inputTentativa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputTentativa.setText("100");
        inputTentativa.setToolTipText("");
        inputTentativa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        inputTentativa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputTentativa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputTentativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTentativaActionPerformed(evt);
            }
        });

        botaoEnviarTentativa.setBackground(new java.awt.Color(0, 153, 153));
        botaoEnviarTentativa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoEnviarTentativa.setText("ENVIAR TENTATIVA");
        botaoEnviarTentativa.setAlignmentX(0.5F);
        botaoEnviarTentativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarTentativaActionPerformed(evt);
            }
        });

        txtFeedBack.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        txtFeedBack.setForeground(new java.awt.Color(255, 255, 255));
        txtFeedBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFeedBack.setText("Por favor digite um nùmero entre 1 e 100");

        txtStatusTentativas.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        txtStatusTentativas.setForeground(new java.awt.Color(255, 255, 255));
        txtStatusTentativas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtStatusTentativas.setText("Você ainda tem 4 tentativas");

        botaoJogarNovamente.setBackground(new java.awt.Color(0, 153, 153));
        botaoJogarNovamente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoJogarNovamente.setText("JOGAR NOVAMENTE");
        botaoJogarNovamente.setAlignmentX(0.5F);
        botaoJogarNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogarNovamenteActionPerformed(evt);
            }
        });

        botaoFecharJogo.setBackground(new java.awt.Color(0, 153, 153));
        botaoFecharJogo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoFecharJogo.setText("FECHAR O JOGO");
        botaoFecharJogo.setAlignmentX(0.5F);
        botaoFecharJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharJogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(tituloMaior, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(tituloMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtFeedBack, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(txtInputTentativa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputTentativa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(botaoJogarNovamente)
                        .addGap(18, 18, 18)
                        .addComponent(botaoFecharJogo)))
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtStatusTentativas)
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoEnviarTentativa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(265, 265, 265))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tituloMaior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFeedBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtStatusTentativas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInputTentativa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTentativa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(botaoEnviarTentativa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoJogarNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFecharJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEnviarTentativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarTentativaActionPerformed
        // TODO add your handling code here:
        try {
            int palpite = Integer.parseInt(inputTentativa.getText());

            
            if (palpite < 1 || palpite > 100) {
                txtFeedBack.setText("Por favor, insira um número entre 1 e 100.");
                return;
            }

            if (palpite == numeroSorteado) {
                respostaCerta = true;
                txtFeedBack.setText("Parabéns! Você conseguiu adivinhar em "+ (5 - tentativas + 1)+" tentativas!");
                inputTentativa.setEditable(false);
                botaoEnviarTentativa.setEnabled(false);
                botaoJogarNovamente.setVisible(true);
                botaoFecharJogo.setVisible(true);
            } else if (palpite > numeroSorteado) {
                txtFeedBack.setText("Dica: Tente um número menor.");
            } else {
                txtFeedBack.setText("Dica: Tente um número maior.");
            }

            tentativas--;
            txtStatusTentativas.setText("Tentativas restantes: " + tentativas);

            if (tentativas == 0 && !respostaCerta) {
                txtFeedBack.setText("Você perdeu! O número era: " + numeroSorteado);
                inputTentativa.setEditable(false);
                botaoEnviarTentativa.setEnabled(false);
                botaoJogarNovamente.setVisible(true);
                botaoFecharJogo.setVisible(true);
            }

        } catch (NumberFormatException ex) {
            txtFeedBack.setText("Por favor, insira um número válido.");
        }
    }//GEN-LAST:event_botaoEnviarTentativaActionPerformed

    private void inputTentativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTentativaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTentativaActionPerformed

    private void botaoJogarNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoJogarNovamenteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ViewJogoDeAdivinhacao().setVisible(true);
    }//GEN-LAST:event_botaoJogarNovamenteActionPerformed

    private void botaoFecharJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharJogoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botaoFecharJogoActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewJogoDeAdivinhacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewJogoDeAdivinhacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewJogoDeAdivinhacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewJogoDeAdivinhacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewJogoDeAdivinhacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviarTentativa;
    private javax.swing.JButton botaoFecharJogo;
    private javax.swing.JButton botaoJogarNovamente;
    private javax.swing.JTextField inputTentativa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloMaior;
    private javax.swing.JLabel tituloMenor;
    private javax.swing.JLabel txtFeedBack;
    private javax.swing.JLabel txtInputTentativa;
    private javax.swing.JLabel txtStatusTentativas;
    // End of variables declaration//GEN-END:variables
}
